# -*- coding: utf-8 -*-
"""model_building.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H8HY9eC03VtQ47WPwFu5pFyTcXTu7-xo
"""

import numpy as np
import pandas as pd
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
import joblib

# 1. Load dataset
wine = load_wine()
X = pd.DataFrame(wine.data, columns=wine.feature_names)
y = wine.target

# 2. Feature selection (choose 6)
selected_features = [
    "alcohol",
    "malic_acid",
    "ash",
    "magnesium",
    "flavanoids",
    "proline"
]

X = X[selected_features]

# 3. Handle missing values (just in case)
print("Missing values:\n", X.isnull().sum())
X = X.fillna(X.mean())

# 4. Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# 5. Feature scaling (MANDATORY)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# 6. Train model
model = LogisticRegression(max_iter=300)
model.fit(X_train_scaled, y_train)

# 7. Evaluate
y_pred = model.predict(X_test_scaled)
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nClassification Report:\n", classification_report(y_test, y_pred))

# 8. Save model + scaler
joblib.dump(model, "wine_cultivar_model.pkl")
joblib.dump(scaler, "scaler.pkl")

print("Model and scaler saved.")